services:
  s3filehandler:
    image: s3filehandler:dev
    build:
      context: ./s3filehandler/
      dockerfile: Dockerfile
    depends_on:
      operations-db:
        condition: service_started
        restart: true
    deploy:
      mode: replicated
      replicas: 2
    environment:
      TZ: Asia/Kolkata
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:postgresql://$POSTGRESQL_SERVER_HOST:$POSTGRESQL_SERVER_PORT/$POSTGRESQL_DATABASE?useSSL=false",
        "spring.datasource.username" : "$POSTGRESQL_USER",
        "spring.datasource.password" : "$POSTGRESQL_USER_PASSWORD",
        "spring.jpa.database" : "POSTGRESQL",
        "show-sql" : "true",
        "spring.minio.url" : "http://minio:9000",
        "minio.credentials.access.key" : "msBOBrevnIT0rHM5urFH",
        "minio.credentials.secret.key" : "SNp6gbBq9rVjOcAfJcuSymy2JcqAS2LaDfx2yucf"
      }'
    volumes:
      - filehandler_storage:/site/uploads

  minio:
    image: minio/minio
    depends_on:
      operations-db:
        condition: service_started
        restart: true
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      - MINIO_ROOT_USER=eversyncops
      - MINIO_ROOT_PASSWORD=StrongPass1#
    command: server --console-address ":9001" /data
    restart: always

volumes:
  minio_storage: {}
  filehandler_storage: {}