server:
  port: 8088
spring:
  application:
    name: S3FileHandler
  datasource:
    url: jdbc:postgresql://operations-db:5432/eversyncops
    username: abcd23
    password: sdfif
  jpa:
    database: POSTGRESQL
    show-sql: true
    open-in-view: false